# Site settings
title: "Bestiary"
author: "chisaipete"
description:
  "A searchable D&D 5e creature list."
baseurl: "/bestiary" # the subpath of your site, e.g. /blog/
url: "http://chisaipete.github.io" # the base hostname & protocol for your site
source-url: "https://github.com/chisaipete/bestiary/"
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

encoding: utf-8

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "creatures"